services:
  - docker

before_install:
  - docker pull pandoc/latex:2.9.2
  - docker run --volume "`pwd`:/data" --entrypoint '/data/docker.sh' pandoc/latex:latest
script:
  - make pandoc-deploy
deploy:
  skip_cleanup: true
  local_dir: output
  region: us-west-2
  provider: s3
  access_key_id: AKIAJWS554QGKBTMSBCA
  secret_access_key:
    secure: DvvRo4SBpjLMR1C02CzxK6Ah2y8jPA+44MjtbngF33D9V9GEzEhUNw29eGSJApitYQyWMjIDJcbkrFiQ7EDpNz+PbqJCrNBEXzPJ86hliEafOVs68XinvIl0T4b74HBxGFpyvCs/3ghhQST8eAT7eClfwlfsgNYEcEsNZqtAO
  bucket: cabforum-travis-artifacts
  upload-dir: builds/$TRAVIS_BRANCH
  acl: public_read
  on:
    all_branches: true
    repo: cabforum/documents
